### ISSUE TITLE
VS Code Plugin

### ISSUE THREAD

**Issue by LefterisXris** [LefterisXris/CodeTour#11]
Steps:
- [ ] Check VSCode guide [Extension API](https://code.visualstudio.com/api)
- [ ] Create a simple navigation plugin
- [ ] Add the read from configuration functionality #14
- [ ] Add the input configuration functionality #13 
- [ ] Release it to the store
- [ ] Enhance it

Functionality and UI should match with #10

**Comment by LefterisXris** [comment]
Seems like a similar tool already exists.
It is actually a great tool! [CodeTour - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour&ssr=false#overview)

**Comment by achat** [comment]
Indeed, it offers similar functionality. It would be nice if we could add some kind of 'intelligence', e.g. follow different paths in the tour depending on the profile of the user, points of interest, etc.

**Comment by LefterisXris** [comment]
Won't proceed on VS Code related implementation due to the existing great [CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) plugin.
Let's focus on #10 
Closing this one
