### ISSUE TITLE
Thesis Paper

### ISSUE THREAD

**Issue by LefterisXris** [LefterisXris/CodeTour#4]
All the related assets can be found on [OneDrive](https://uomak-my.sharepoint.com/:f:/g/personal/mai21066_delos365_uom_gr/EkzaF9J3ashEru3PARFw-u0B3ySPDAPclXs7iQwfcCo8eg?e=SPjvml)

The goal is to apply for at least one publication. To do that we should mind for:
- [x] Availables magazines/conferences
  - [x] It would be wise to check for IntelliJ and/or VSCode plugins related conferences to promote our work
- [x] Check the available dates for the publications (for submission)
- [x] Be accepted at least to one
- [x] ~~Prepare the related paper document and any other assets~~

**Conferences and Submissions in comments**

**Comment by LefterisXris** [comment]
Take a look at
- Developers Week [Call for Speakers](https://www.developerweek.com/conference/call-for-speakers/?fbclid=IwAR0LF-nRxNUhTnSi0ZF6qDyfgANz0HUxbV35gU3QMkAgOdREQuVzMN2Wwak) due at 03Dec21

**Comment by LefterisXris** [comment]
- Public Speaker profile created https://sessionize.com/eleftherios-chrysochoidis
- Submitted official session on 23Nov21 for DeveloperWeek 2022 on [DevLead Track](https://www.developerweek.com/conference/devlead-conference/). 
- Submission is currently in evaluation.

Listing other potential/candidate events:

- [ ] [DeveloperWeek 2022-Europe](https://www.developerweek.com/europe/conference/conference-tracks/) hold in `27-28Apr22`. Submission due date: `18Mar22`
- [ ] [DevSum](https://www.devsum.se/) hold in `18-21May22`. Submission due date: `14Dec21`

**Comment by LefterisXris** [comment]
Unfortunately I got rejected from DeveloperWeek 2022

**Comment by achat** [comment]
How is that? Do they have entry criteria for the DeveloperWeek?

**Comment by LefterisXris** [comment]
@achat No entry criteria were mentioned. Registration was open and free to anyone. The only requirement was to suggest a good idea/topic. The available sessions were limited as there were many PRO sessions (with KeyNote/Invited/Featured Speakers).

DeveloperWeek Conference has 15+ Tracks (Full list here https://www.developerweek.com/conference/conference-tracks/) and I applied for DevLEAD. As far as I can see from the final schedule, it seems that many good talks were selected and the majority of the selected speakers are way more experienced than me. e.g. CEOs, CTOs, Directors, Google/Facebook/CNN employees etc. Full list of speakers and scedule is available here https://www.developerweek.com/conference/devlead-conference/

To sum up, I think they evaluated based on the following (just my thoughts, not verified):
- Speaker Bio (Sessionize provides that info, but I created my profile just before the sumbission, so 1 sumbission, 0 history)
- Personal Bio (I got some experience, but comparing to the selected ones... it's not enough) 
- Statement (I could probably promote it better)


By the way, I am attaching my submitted statement (I know, I have a typo on the title, on `Practises` 😊):
![image](https://user-images.githubusercontent.com/22836249/149030990-f567ec8f-db82-482d-8a45-b58a8c321026.png)

And their response (by email):
```
Hi Eleftherios,

Thank you for submitting a speaker proposal for the DeveloperWeek 2022 Call for Speakers!  

We truly value your time spent proposing a session for this year's annual DeveloperWeek 2022,
virtually globally online, Feb 7-9, 2022.  We've had a record large number of proposals for our 
10th annual DeveloperWeek 2022, and unfortunately, we are unable to accept your proposal
this year: Cost of Code Understanding and Best Practises

This doesn't reflect negatively on your proposal at all. We always have very limited speaking 
opportunities per conference track & topic, and we receive far too many high-quality proposals
than our final agenda will allow.
```

**Comment by achat** [comment]
Don't worry. The statement is perfect. As you said, they probably want to bring in as many CEOs as possible :-)

**Comment by LefterisXris** [comment]
We are in!! https://emamo.com/event/developerweek-2022/r/speaker/eleftherios-chrysochoidis
Developer Week  **09Feb22** - `OPEN TALK: Cost of Code Understanding and Best Practices`

**Comment by LefterisXris** [comment]
Overall outcome is 1 out of 5 Conferences. Not bad for a new joiner 😊 (in terms of public speaker)

 `DeveloperWeek` was a challenging and great experience. To be honest, online conferences cannot be compared to the live ones, and I hope that eventually, I will manage to present something live.
