### ISSUE TITLE
Improved Support for File Paths

### ISSUE THREAD

**Issue by DavidSeptimus** [LefterisXris/CodeTour#64]
### Description
Currently, the plugin only supports simple file names in a step's `file` property and also ignores the `directory` property when looking up files. This breaks compatibility with tours developed in VS Code since that plugin writes directory/workspace relative paths to a step's `file` property. Additionally, as noted in the existing codebase, looking up files by filename alone results in conflicts when a project contains multiple files with the same name.

### Solution
**Describe the solution you'd like**
To improve file path handling, assume the value of the `file` property is relative to the project base directory+ the value of the `directory` property.

### Example 
Given the following step:
```json
    {
      "title": "TourStepGeneratorAction.java:7",
      "description": "some explanation",
      "directory": "src/main/java"
      "file": "org/uom/lefterisxris/codetour/tours/actions/TourStepGeneratorAction.java",
      "line": 7
    }
```
The plugin should find the file at `$PROJECT_DIR$/src/main/java/org/uom/lefterisxris/codetour/tours/actions/TourStepGeneratorAction.java`

### Additional Context
Note that this would also entail handling os-specific path separators.

It's also important to call out that this would be a breaking change impacting tours that depend on filename-based lookup of files not located in `$PROJECT_DIR$` unless maintaining the existing functionality as a fallback for when the file can't be found using relative paths.

**Comment by LefterisXris** [comment]
That's right @DavidSeptimus! It's a really good point and should be done.
I will check @Noyloy 's PR and will release a patch version for this one.

**Comment by LefterisXris** [comment]
Issue auto-closed through automation, after PR merge. Feature will be included on the upcoming release (soon)
