### ISSUE TITLE
Can't work on IDEA 2023.1

### ISSUE THREAD

**Issue by ooooo84** [LefterisXris/CodeTour#74]
**Is your feature request related to a problem? Please describe.**
Can't work on IDEA 2023.1

**Describe the solution you'd like**
Work properly on IDEA 2023.1

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by LefterisXris** [comment]
Thanks for the notice @ooooo84 . I will release a new version soon!

**Comment by LefterisXris** [comment]
📢 CodeTour v0.0.8 has been released. A typical review from Jetbrains' team is pending, and after that, the new version will be available!

In the meanwhile, feel free to suggest, comment or complain about anything related to the plugin, on the discussions area https://github.com/LefterisXris/CodeTour/discussions/76

🎉 https://plugins.jetbrains.com/plugin/19227-codetour
