### ISSUE TITLE
BUG: not compatible with IDEA 2023.2

### ISSUE THREAD

**Issue by ooooo84** [LefterisXris/CodeTour#78]
**Describe the bug**
Not compatible with IDEA 2023.2

**To Reproduce**
Upgrade to IDEA 2023.2

**Expected behavior**
Plugin works well

**Screenshots**
None

**System (please complete the following information):**

- OS: Windows 10
- IDE: IntelliJ Ultimate
- IDE Version: 2023.2
- Plugin Version: 0.0.8

**Additional context**
None

**Comment by LefterisXris** [comment]
A new version, compatible with 2023.* has been deployed and is available in the Marketplace.
Please update the plugin via JetBrains' `Plugins` feature to make sure the latest version (CodeTour `0.0.9`) is installed.
